name: prueba_flutter
description: "Prueba App Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  http: ^1.4.0
  shared_preferences: ^2.5.3
  http_interceptor: ^2.0.0
  image_picker: ^1.1.2
  image_cropper: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
